INSERT INTO PUBLIC.OPERATION_TYPE (ID, DESCRIPTION) VALUES(1, 'COMPRA A VISTA');
INSERT INTO PUBLIC.OPERATION_TYPE (ID, DESCRIPTION) VALUES(2, 'COMPRA PARCELADA');
INSERT INTO PUBLIC.OPERATION_TYPE (ID, DESCRIPTION) VALUES(3, 'SAQUE');
INSERT INTO PUBLIC.OPERATION_TYPE (ID, DESCRIPTION) VALUES(4, 'PAGAMENTO');
